---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/roniel22/gomoveinfra.com.br/
    - /bin/cp -R dist/assets "$DEPLOYPATH"
    - /bin/cp -R dist/brand "$DEPLOYPATH"
    - /bin/cp dist/index.html "$DEPLOYPATH"
    - /bin/cp dist/.htaccess "$DEPLOYPATH"
